using System;

namespace NetFwTypeLib
{
	public enum NET_FW_SERVICE_TYPE_
	{
		NET_FW_SERVICE_FILE_AND_PRINT,
		NET_FW_SERVICE_UPNP,
		NET_FW_SERVICE_REMOTE_DESKTOP,
		NET_FW_SERVICE_NONE,
		NET_FW_SERVICE_TYPE_MAX
	}
}
